import { defineStrings } from '../_lib/core/strings.js';

defineStrings({
  'update-banner.available':  'Update available',
  'update-banner.reload':     'Reload',
  'update-banner.dismiss':    'Dismiss',

  'home-page.capstone-section':     'Capstone',
  'home-page.milestone-section':    '3-Month Milestones',
  'home-page.wow-section':          '8-Week Wow',
  'home-page.focus-section':        'Forward Focus',
  'home-page.prev-year':         'Previous year',
  'home-page.next-year':         'Next year',
  'home-page.year-progress':     'Year progress',
  'home-page.done':              'Done',

  'goal-dialog.heading':     'Set your goal',
  'goal-dialog.placeholder': 'What will you achieve this year?',
  'goal-dialog.description-placeholder': 'Description',
  'goal-dialog.save':        'Save',
  'goal-dialog.cancel':      'Cancel',
  'goal-dialog.delete':         'Delete',
  'goal-dialog.delete-confirm': 'Sure?',

  'goal-item.delete':          'Delete',
  'goal-item.delete-confirm':  'Sure?',
  'goal-item.fail':            'Fail',
  'goal-item.restore':         'Restore',
  'goal-item.add-capstone':    'Add capstone goal',
  'goal-item.add-milestone':   'Add milestone',
  'goal-item.add-wow':         'Add wow moment',
  'goal-item.add-focus':       'Add to Forward Focus',
  'goal-item.status-failed':   'Goal marked as failed',
  'goal-item.status-restored': 'Goal restored',
  'goal-item.drag':            'Drag to reorder',

  'home.toast-goal-saved':   'Goal saved',
  'home.toast-goal-deleted': 'Goal deleted',

  'year-header.menu':         'Menu',
  'year-header.year-section': 'This year',
  'year-header.app-section':  'App',
  'year-header.language':     'Language',
  'year-header.version':      'Version',
  'year-header.photo':        'Year photo',
  'year-header.photo-add':    'Add photo',
  'year-header.photo-change': 'Change photo',
  'year-header.photo-remove': 'Remove photo',
  'year-header.color':        'Year color',
  'year-header.color-reset':  'Reset to default',
  'year-header.theme':        'Appearance',
  'year-header.theme-light':  'Light',
  'year-header.theme-dark':   'Dark',
  'year-header.theme-system': 'System',

  'not-found.heading': 'Nothing here',
  'not-found.body':    "This page doesn't exist — but your goals are waiting.",
  'not-found.cta':     'Go to this year',

  'sync.export-year': 'Export {year}',
  'sync.export-all':  'Export data',
  'sync.import':      'Import',
  'sync.import-preview':         'This file has {description}.',
  'sync.import-preview-empty':   'This file has no goals or list items.',
  'sync.import-preview-log':     'This file has {count} events.',
  'sync.import-cancel':          'Cancel',
  'sync.import-merge':           'Merge',
  'sync.import-replace':         'Replace all',
  'sync.import-sure':            'Sure?',
  'sync.import-sure-aria':       'Confirm: replace all data',
  'sync.import-confirm':         'Added {goals} goals and {items} list items.',
  'sync.import-replace-confirm': 'All data replaced.',
  'sync.import-close':           'Close',
  'sync.import-error':           'Invalid or incompatible export file.',

  'lists-page.heading': 'Lists',
  'lists-page.empty':   'No lists yet',
  'lists-page.add':     'New list',
  'lists-page.edit':    'Edit',

  'list-detail.back':        'Lists',
  'list-detail.empty':       'No items yet',
  'list-detail.add':         'New item',
  'list-detail.menu':        'Options',
  'list-detail.show-status':  'Show status',
  'list-detail.hide-status':  'Hide status',
  'list-detail.status-label': 'Status',
  'list-detail.status-show':  'Show',
  'list-detail.status-hide':  'Hide',

  'list-dialog.heading-create':   'New list',
  'list-dialog.heading-edit':     'Edit list',
  'list-dialog.name-placeholder': 'List name',
  'list-dialog.color-label':       'Colour',
  'list-dialog.save':             'Save',
  'list-dialog.cancel':           'Cancel',
  'list-dialog.delete':           'Delete',
  'list-dialog.delete-confirm':   'Sure?',

  'item-dialog.heading-create':   'New item',
  'item-dialog.heading-edit':     'Edit item',
  'item-dialog.title-placeholder':'Title',
  'item-dialog.status-label':     'Status',
  'item-dialog.status-open':      'Open',
  'item-dialog.status-paused':    'Paused',
  'item-dialog.status-done':      'Done',
  'item-dialog.note-placeholder': 'Note',
  'item-dialog.url-placeholder':  'Link (https://…)',
  'item-dialog.url-toggle':       'Link',
  'item-dialog.url-open':         'Open',
  'item-dialog.save':             'Save',
  'item-dialog.cancel':           'Cancel',
  'item-dialog.delete':           'Delete',
  'item-dialog.delete-confirm':   'Sure?',

  'list-item.delete':          'Delete',
  'list-item.delete-confirm':  'Sure?',
  'list-item.mark-done': 'Mark done',
  'list-item.restore':   'Restore',

  'lists.toast-list-saved':   'List saved',
  'lists.toast-list-deleted': 'List deleted',
  'lists.toast-item-saved':   'Item saved',
  'lists.toast-item-deleted': 'Item deleted',

  'year-header.lists': 'Lists',

  'bottom-nav.years':    'Years',
  'bottom-nav.lists':    'Lists',
  'bottom-nav.settings': 'Settings',

  'settings.repair':       'Repair installation',
  'sync.backup-downloaded': 'Your data has been backed up before the update.',
});
