import { defineStrings } from '../_lib/core/strings.js';

defineStrings({
  'update-banner.available':  'Update available',
  'update-banner.reload':     'Reload',
  'update-banner.dismiss':    'Dismiss',

  'home-page.capstone-section':     'Capstone',
  'home-page.milestone-section':    '3-Month Milestones',
  'home-page.wow-section':          '8-Week Wow',
  'home-page.focus-section':        'Forward Focus',
  'home-page.prev-year':         'Previous year',
  'home-page.next-year':         'Next year',
  'home-page.year-progress':     'Year progress',
  'home-page.done':              'Done',

  'goal-dialog.heading':     'Set your goal',
  'goal-dialog.placeholder': 'What will you achieve this year?',
  'goal-dialog.description-placeholder': 'Description',
  'goal-dialog.copy-description': 'Copy description',
  'goal-dialog.save':        'Save',
  'goal-dialog.cancel':      'Cancel',
  'goal-dialog.delete':         'Delete',
  'goal-dialog.delete-confirm': 'Sure?',

  'goal-item.delete':          'Delete',
  'goal-item.delete-confirm':  'Sure?',
  'goal-item.add-capstone':    'Add capstone goal',
  'goal-item.add-milestone':   'Add milestone',
  'goal-item.add-wow':         'Add wow moment',
  'goal-item.add-focus':       'Add to Forward Focus',
  'goal-item.drag':            'Drag to reorder',

  'home.toast-goal-saved':   'Goal saved',
  'home.toast-goal-deleted': 'Goal deleted',
  'home.toast-goal-moved':         'Goal moved to {section}',
  'home.toast-goal-copied':        'Goal copied to {section}',
  'home.toast-item-created':       'Added to {name}',
  'home.toast-item-created-many':  'Added to {n} lists',

  'goal-dialog.more-actions':            'More actions',
  'goal-dialog.move-to-year':            'Move to year',
  'goal-dialog.create-list-item':        'Create list item',
  'goal-dialog.move-year-label':         'Year',
  'goal-dialog.move-section-label':      'Section',
  'goal-dialog.move-section-capstone':   'Capstone',
  'goal-dialog.move-section-milestones': 'Milestones',
  'goal-dialog.move-section-wow':        'Wow Moments',
  'goal-dialog.move-section-focus':      'Focus',
  'goal-dialog.move-cta':               'Move',
  'goal-dialog.copy-cta':               'Copy',
  'goal-dialog.picker-back':            'Back',

  'year-header.menu':         'Menu',
  'year-header.year-section': 'This year',
  'year-header.app-section':  'App',
  'year-header.language':     'Language',
  'year-header.version':      'Version',
  'year-header.photo':        'Year photo',
  'year-header.photo-add':    'Add photo',
  'year-header.photo-change': 'Change photo',
  'year-header.photo-remove': 'Remove photo',
  'year-header.color':        'Year color',
  'year-header.color-reset':  'Reset to default',
  'year-header.theme':        'Appearance',
  'year-header.theme-light':  'Light',
  'year-header.theme-dark':   'Dark',
  'year-header.theme-system': 'System',

  'not-found.heading': 'Nothing here',
  'not-found.body':    "This page doesn't exist — but your goals are waiting.",
  'not-found.cta':     'Go to this year',

  'sync.export-year': 'Export {year}',
  'sync.export-all':  'Export data',
  'sync.import':      'Import',
  'sync.import-preview':         'This file has {description}.',
  'sync.import-preview-empty':   'This file has no goals or list items.',
  'sync.import-preview-log':     'This file has {count} events.',
  'sync.import-cancel':          'Cancel',
  'sync.import-merge':           'Merge',
  'sync.import-replace':         'Replace all',
  'sync.import-sure':            'Sure?',
  'sync.import-sure-aria':       'Confirm: replace all data',
  'sync.import-confirm':         'Added {goals} goals and {items} list items.',
  'sync.import-replace-confirm': 'All data replaced.',
  'sync.import-close':           'Close',
  'sync.import-error':           'Invalid or incompatible export file.',

  'lists-page.heading':   'Lists',
  'lists-page.empty':     'No lists yet',
  'lists-page.add':       'New list',
  'lists-page.drag':     'Drag to reorder',

  'list-detail.back':        'Lists',
  'list-detail.empty':       'No items yet',
  'list-detail.add':         'New item',
  'list-detail.menu':        'Options',
  'list-detail.edit-name':   'Edit list name',
  'list-detail.delete-list':         'Delete list',
  'list-detail.delete-list-confirm': 'Sure?',
  'list-detail.show-status':  'Show status',
  'list-detail.hide-status':  'Hide status',
  'list-detail.status-label': 'Status',
  'list-detail.status-show':        'Show',
  'list-detail.status-hide':        'Hide',
  'list-detail.cancel-selection':   'Cancel',
  'list-detail.selection-count':    '{n} items',
  'list-detail.bulk-delete':        'Delete',
  'list-detail.bulk-status':        'Status',
  'list-detail.bulk-move':          'Move',
  'list-detail.bulk-more':          'More',
  'list-detail.bulk-status-label':  'Set Status',
  'list-detail.bulk-more-label':    'Actions',
  'list-detail.bulk-delete-toast':  'Deleted {n} items',
  'list-detail.bulk-status-toast':  'Updated {n} items',

  'list-dialog.heading-create':   'New list',
  'list-dialog.heading-edit':     'Edit list',
  'list-dialog.name-placeholder': 'List name',
  'list-dialog.color-label':       'Colour',
  'list-dialog.save':             'Save',
  'list-dialog.cancel':           'Cancel',
  'list-dialog.delete':           'Delete',
  'list-dialog.delete-confirm':   'Sure?',

  'item-dialog.heading-create':   'New item',
  'item-dialog.heading-edit':     'Edit item',
  'item-dialog.title-placeholder':'Title',
  'item-dialog.status-label':     'Status',
  'item-dialog.status-open':      'Open',
  'item-dialog.status-paused':    'Paused',
  'item-dialog.status-done':      'Done',
  'item-dialog.note-placeholder': 'Note',
  'item-dialog.copy-note': 'Copy note',
  'item-dialog.url-placeholder':  'Link (https://…)',
  'item-dialog.url-toggle':       'Link',
  'item-dialog.url-open':         'Open',
  'item-dialog.save':             'Save',
  'item-dialog.cancel':           'Cancel',
  'item-dialog.delete':           'Delete',
  'item-dialog.delete-confirm':   'Sure?',

  'item-dialog.move-to-list':           'Move to list',
  'item-dialog.add-to-goal':            'Add to goal',
  'item-dialog.picker-back':            'Back',
  'item-dialog.move-cta':               'Move',
  'item-dialog.copy-cta':               'Copy',
  'item-dialog.no-other-lists':         'No other lists',
  'item-dialog.new-list-btn':           '＋ New list',
  'item-dialog.new-list-placeholder':   'List name',
  'item-dialog.goal-year-label':        'Year',
  'item-dialog.goal-section-label':     'Section',
  'item-dialog.goal-section-capstone':  'Capstone',
  'item-dialog.goal-section-milestones':'Milestones',
  'item-dialog.goal-section-wow':       'Wow Moments',
  'item-dialog.goal-section-focus':     'Focus',
  'item-dialog.goal-add-cta':           'Add to goal',
  'item-dialog.goal-already-added':     'Already added',
  'item-dialog.in-goals-label':         'In goals',
  'item-dialog.move-toast':             'Moved to {name}',
  'item-dialog.move-toast-many':        'Moved to {n} lists',
  'item-dialog.copy-toast':             'Copied to {name}',
  'item-dialog.copy-toast-many':        'Copied to {n} lists',
  'item-dialog.promote-toast':          'Added to {year} {section}',
  'item-dialog.more-actions':           'More actions',
  'item-dialog.picker-selected':        '{n} selected',
  'item-dialog.picker-clear':           'Clear selection',

  'list-item.delete':          'Delete',
  'list-item.delete-confirm':  'Sure?',
  'list-item.mark-done': 'Mark done',
  'list-item.restore':   'Restore',
  'list-item.drag':      'Drag to reorder',

  'lists.toast-list-saved':   'List saved',
  'lists.toast-list-deleted': 'List deleted',
  'lists.toast-item-saved':   'Item saved',
  'lists.toast-item-deleted': 'Item deleted',

  'year-header.lists': 'Lists',

  'bottom-nav.years':    'Years',
  'bottom-nav.lists':    'Lists',
  'bottom-nav.settings': 'Settings',

  'settings.repair':       'Repair installation',
  'sync.backup-downloaded': 'Your data has been backed up before the update.',
});
