import { defineStrings } from '../_lib/core/strings.js';

defineStrings({
  'update-banner.available':  'Update available',
  'update-banner.reload':     'Reload',
  'update-banner.dismiss':    'Dismiss',

  'home-page.capstone-section':     'Capstone',
  'home-page.milestone-section':    '3-Month Milestones',
  'home-page.wow-section':          '8-Week Wow',
  'home-page.focus-section':        'Forward Focus',
  'home-page.prev-year':         'Previous year',
  'home-page.next-year':         'Next year',
  'home-page.year-progress':     'Year progress',
  'home-page.done':              'Done',

  'goal-dialog.placeholder': 'What will you achieve this year?',
  'goal-dialog.notes-placeholder': 'Notes',
  'goal-dialog.copy-notes': 'Copy notes',
  'goal-dialog.close':           'Close',
  'goal-dialog.save-and-close': 'Save and close',
  'goal-dialog.title-new':      'New goal',
  'goal-dialog.title-edit':     'Edit goal',
  'goal-dialog.delete':         'Delete',

  'goal-item.delete':          'Delete',
  'goal-item.add-capstone':    'Add capstone goal',
  'goal-item.add-milestone':   'Add milestone',
  'goal-item.add-wow':         'Add wow moment',
  'goal-item.add-focus':       'Add to Forward Focus',
  'goal-item.drag':            'Drag to reorder',

  'home.toast-goal-saved':   'Goal saved',
  'home.toast-goal-deleted': 'Goal deleted',
  'home.toast-goal-moved':         'Goal moved to {section}',
  'home.toast-goal-copied':        'Goal copied to {section}',
  'home.toast-goal-archived':      'Goal archived',
  'home.toast-goal-unarchived':    'Goal unarchived',
  'home.toast-item-created':       'Added to {name}',
  'home.toast-item-created-many':  'Added to {n} lists',

  'goal-dialog.tags-label':              'Tags',
  'goal-dialog.tags-placeholder':        'Add tag…',

  'goal-dialog.more-actions':            'More actions',
  'goal-dialog.archive':                 'Archive',
  'goal-dialog.unarchive':               'Unarchive',
  'goal-dialog.move-to-year':            'Move to year',
  'goal-dialog.create-list-item':        'Create list item',
  'goal-dialog.move-year-label':         'Year',
  'goal-dialog.move-section-label':      'Section',
  'goal-dialog.move-section-capstone':   'Capstone',
  'goal-dialog.move-section-milestones': 'Milestones',
  'goal-dialog.move-section-wow':        'Wow Moments',
  'goal-dialog.move-section-focus':      'Focus',
  'goal-dialog.move-cta':               'Move',
  'goal-dialog.copy-cta':               'Copy',
  'goal-dialog.picker-back':            'Back',

  'year-header.menu':         'Menu',
  'year-header.year-section': 'This year',
  'year-header.app-section':  'App',
  'year-header.language':     'Language',
  'year-header.version':      'Version',
  'year-header.photo':        'Year photo',
  'year-header.photo-add':    'Add photo',
  'year-header.photo-change': 'Change photo',
  'year-header.photo-remove': 'Remove photo',
  'year-header.color':           'Year color',
  'year-header.color-reset':     'Reset to default',
  'year-header.color-sky-blue':  'Sky blue',
  'year-header.color-blue':      'Blue',
  'year-header.color-indigo':    'Indigo',
  'year-header.color-violet':    'Violet',
  'year-header.color-pink':      'Pink',
  'year-header.color-red':       'Red',
  'year-header.color-orange':    'Orange',
  'year-header.color-yellow':    'Yellow',
  'year-header.color-green':     'Green',
  'year-header.color-teal':      'Teal',
  'year-header.theme':        'Appearance',
  'year-header.theme-light':  'Light',
  'year-header.theme-dark':   'Dark',
  'year-header.theme-system': 'System',
  'year-header.extract-markdown': 'Extract Markdown',

  'not-found.heading': 'Nothing here',
  'not-found.body':    "This page doesn't exist — but your goals are waiting.",
  'not-found.cta':     'Go to this year',

  'sync.export-all':  'Export data',
  'sync.import':      'Import',
  'sync.import-preview':         'This file has {description}.',
  'sync.import-preview-empty':   'This file has no goals or list items.',
  'sync.import-preview-log':     'This file has {count} events.',
  'sync.preview-goals-one':      '{n} goal ({years})',
  'sync.preview-goals-many':     '{n} goals ({years})',
  'sync.preview-lists-one':      '{n} list with {items}',
  'sync.preview-lists-many':     '{n} lists with {items}',
  'sync.preview-items-one':      '{n} item',
  'sync.preview-items-many':     '{n} items',
  'sync.preview-and':            ' and ',
  'sync.import-cancel':          'Cancel',
  'sync.import-merge':           'Merge',
  'sync.import-replace':         'Replace all',
  'sync.import-sure':            'Sure?',
  'sync.import-sure-aria':       'Confirm: replace all data',
  'sync.import-confirm':         'Added {goals} goals and {items} list items.',
  'sync.import-replace-confirm': 'All data replaced.',
  'sync.import-close':           'Close',
  'sync.import-error':           'Invalid or incompatible export file.',

  'lists-page.heading':   'Lists',
  'lists-page.add':       'New list',
  'lists-page.drag':     'Drag to reorder',

  'list-detail.back':        'Lists',
  'list-detail.add':         'New item',
  'list-detail.menu':        'Options',
  'list-detail.edit-name':   'Edit list name',
  'list-detail.delete-list':         'Delete list',
  'list-detail.status-label': 'Status',
  'list-detail.status-show':        'Show',
  'list-detail.status-hide':        'Hide',
  'list-detail.cancel-selection':   'Cancel',
  'list-detail.selection-count':    '{n} items',
  'list-detail.bulk-delete':        'Delete',
  'list-detail.bulk-status':        'Status',
  'list-detail.bulk-move':          'Move',
  'list-detail.bulk-more':          'More',
  'list-detail.bulk-status-label':  'Set Status',
  'list-detail.extract-markdown':      'Extract Markdown',
  'list-detail.bulk-extract-markdown': 'Extract Markdown',
  'list-detail.bulk-delete-toast':  'Deleted {n} items',
  'list-detail.bulk-status-toast':  'Updated {n} items',

  'list-dialog.name-placeholder': 'List name',
  'list-dialog.close':            'Close',
  'list-dialog.save-and-close':   'Save and close',
  'list-dialog.title-new':        'New list',
  'list-dialog.title-edit':       'Edit list',
  'list-dialog.delete':           'Delete',

  'item-dialog.title-placeholder':'Title',
  'item-dialog.status-label':     'Status',
  'item-dialog.status-open':      'Open',
  'item-dialog.status-paused':    'Paused',
  'item-dialog.status-done':      'Done',
  'item-dialog.status-closed':    'Closed',
  'item-dialog.note-placeholder': 'Note',
  'item-dialog.copy-note': 'Copy note',
  'item-dialog.url-placeholder':  'Link (https://…)',
  'item-dialog.url-toggle':       'Link',
  'item-dialog.url-open':         'Open',
  'item-dialog.close':            'Close',
  'item-dialog.save-and-close':   'Save and close',
  'item-dialog.title-new':        'New item',
  'item-dialog.title-edit':       'Edit item',
  'item-dialog.delete':           'Delete',
  'dialog.saved-sr':              'Saved',

  'item-dialog.move-to-list':           'Move to list',
  'item-dialog.add-to-goal':            'Add to goal',
  'item-dialog.extract-markdown':       'Extract Markdown',
  'item-dialog.picker-back':            'Back',
  'item-dialog.move-cta':               'Move',
  'item-dialog.copy-cta':               'Copy',
  'item-dialog.no-other-lists':         'No other lists',
  'item-dialog.new-list-btn':           '＋ New list',
  'item-dialog.new-list-placeholder':   'List name',
  'item-dialog.goal-year-label':        'Year',
  'item-dialog.goal-section-label':     'Section',
  'item-dialog.goal-section-capstone':  'Capstone',
  'item-dialog.goal-section-milestones':'Milestones',
  'item-dialog.goal-section-wow':       'Wow Moments',
  'item-dialog.goal-section-focus':     'Focus',
  'item-dialog.goal-add-cta':           'Add to goal',
  'item-dialog.goal-already-added':     'Already added',
  'item-dialog.in-goals-label':         'In goals',
  'item-dialog.move-toast':             'Moved to {name}',
  'item-dialog.move-toast-many':        'Moved to {n} lists',
  'item-dialog.copy-toast':             'Copied to {name}',
  'item-dialog.copy-toast-many':        'Copied to {n} lists',
  'item-dialog.promote-toast':          'Added to {year} {section}',
  'item-dialog.tags-label':             'Tags',
  'item-dialog.tags-placeholder':       'Add tag…',

  'item-dialog.more-actions':           'More actions',
  'item-dialog.picker-selected':        '{n} selected',
  'item-dialog.picker-clear':           'Clear selection',

  'list-item.delete':          'Delete',
  'list-item.mark-done': 'Mark done',
  'list-item.restore':   'Restore',
  'list-item.drag':      'Drag to reorder',

  'lists.toast-list-saved':   'List saved',
  'lists.toast-list-deleted': '“{name}” deleted',
  'lists.toast-item-saved':   'Item saved',
  'lists.toast-item-deleted': 'Item deleted',

  'list-detail.filter-toggle':        'Filter',
  'list-detail.filter-search':        'Search items…',
  'list-detail.filter-status-all':    'All',
  'list-detail.filter-clear':         'Clear filters',
  'list-detail.filter-expand':        'More filters',
  'list-detail.filter-empty':         'No items match',
  'list-detail.filter-count':         '{count} items match',

  'lists-page.filter-toggle':         'Filter',
  'lists-page.filter-search':         'Search lists…',
  'lists-page.filter-expand':         'More filters',
  'lists-page.filter-clear':          'Clear filters',
  'lists-page.filter-empty':          'No lists match',
  'lists-page.filter-empty-only':     'Empty',
  'lists-page.filter-not-empty':      'Not empty',
  'lists-page.filter-count':          '{count} lists match',

  'home-page.filter-toggle':          'Filter',
  'home-page.filter-search':          'Search goals…',
  'home-page.filter-expand':          'More filters',
  'home-page.filter-done':            'Done',
  'home-page.filter-ongoing':         'Ongoing',
  'home-page.filter-not-started':     'Not started',
  'home-page.filter-archived':        'Archived',
  'home-page.filter-clear':           'Clear filters',
  'home-page.filter-empty':           'No goals match',
  'home-page.filter-count':           '{count} goals match',

  'list-detail.add-from-text':       'Add from text',
  'list-detail.import-heading':      'Import items',
  'list-detail.import-placeholder':  'One item per line. Indent a line to make it a note.',
  'list-detail.import-count':        '{n} items',
  'list-detail.import-count-extras': '{n} items · {m} with notes or links',
  'list-detail.import-cancel':       'Cancel',
  'list-detail.import-cta':          'Import',
  'list-detail.import-toast':        'Imported {n} items',

  'bottom-nav.years':    'Years',
  'bottom-nav.lists':    'Lists',
  'bottom-nav.settings': 'Settings',

  'settings.repair':            'Repair installation',
  'settings.export-reminder':   'Export reminder',
  'settings.reminder-on':       'Show',
  'settings.reminder-off':      'Hide',
  'settings.tag-strip':         'Tag colours',
  'settings.tags-shown':        'Shown',
  'settings.tags-hidden':       'Hidden',
  'sync.backup-downloaded':     'Your data has been backed up before the update.',
  'sync.backup-before-import':  'Your data has been backed up.',

  'export-sheet.metadata': 'Metadata',
  'export-sheet.notes':    'Notes',
  'export-sheet.extract':  'Extract Markdown',
  'export.copied':         'Copied to clipboard',

  'undo.button':  'Undo',
  'toast.close':  'Close',
  'tag.remove':   'Remove {tag}',
});
